/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package determine.cope.fixpoint;

import org.junit.jupiter.api.Test;

import determine.cope.fixpoint.App;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();

    }
}
